# Chapter47
## 📌문제1
### 다음 코드의 실행 결과를 서술하시오.
```js
const func = (n, f) => {
  if(typeof f !== 'function') new Error('f must be function');
  f(n);
}

try {
  func(1, 2);
}catch(e){
   console.log(e);
}
```
### 답안 작성
```

```

<br>

## 📌문제2

### 다음 코드의 실행 결과를 예상해보고, 의도에 맞게 고치세요.

```js
const practice = (n, f) => {
  if (typeof f !== "function") {
    new TypeError("f must be a function");
  }
};

try {
  practice(2, 1);
  new Error("something wrong");
} catch (error) {
  console.log(error);
}
```

### 답안 작성
```

```

<br>

## 📌문제3
### 다음 코드의 `(1)에서 this`가 무엇일지 작성하고, `(2)전체 실행 출력 결과`를 작성하시오.
```js
const obj = {
  name: 'i am object'
};

async function test2() {
  try {
    throw 123;
  } catch (error) {
    // (1) this
    console.log('test2-catch');
    throw new Error('test2-catch');
  }
}

function test1() {
  try {
    test2.bind(obj)();
    console.log('test1-try');
  } catch (error) {
    console.log('test1-catch');
    throw new Error('test1-catch');
  }
}

try {
  test1()
} catch (error) {
  console.log(error);
}
```
### 답안 작성
```
(1) : 
(2) : 
```

<br>

## 📌문제4
### f1을 실행시켰을때 발생하는 에러를 처리하는 코드를 f1함수내부의 catch문에서 작성하고, 이외의 에러는 "알수 없는 에러 발생" 으로 처리하도록 코드를 작성하세요.
```js
    const f1 = () => {
        try {
          console.log(b);
        } catch (error) {
      // (1)
        }
      };

      try {
        f1();
      } catch (error) {
        console.error("알수 없는 에러 발생");
      }
```
### 답안 작성
```
(1)
```

<br>

