# Chapter47
## 📌문제1
### 다음 코드의 실행 결과를 서술하시오.
```js
const func = (n, f) => {
  if(typeof f !== 'function') new Error('f must be function');
  f(n);
}

try {
  func(1, 2);
}catch(e){
   console.log(e);
}
```
### 정답 및 해설
```
TypeError: f is not a function
error을 throw 하지 않아서 try catch 문에서 에러 처리가 되지 않는다
```

<br>

## 📌문제2

### 다음 코드의 실행 결과를 예상해보고, 의도에 맞게 고치세요.

```js
const practice = (n, f) => {
  if (typeof f !== "function") {
    new TypeError("f must be a function");
  }
};

try {
  practice(2, 1);
  new Error("something wrong");
} catch (error) {
  console.log(error);
}
```

### 답안 작성
```
890p
Error 생성자 함수로 에러 객체를 생성한다고 에러가 발생하는 것은 아닙니다.
즉, 에러 객체 생성과 에러 발생은 의미가 다릅니다.
에러를 발생시키려면 try 코드 블록에서 throw 문으로 에러 객체를 던져야 합니다.
```
```js
const practice = (n, f) => {
  if (typeof f !== "function") {
    throw new TypeError("f must be a function");
  }
};

try {
  practice(2, 1);
  new Error("something wrong");
} catch (error) {
  console.log(error);
}
```

<br>
